baseurl = "http://chehacks.github.io/website" # http://replace-this-with-your-hugo-site.com/
languageCode = "en-us"
title = "CHEHacks II"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "CHEHacks II"
	description = "CHEHacks is a high school hackathon for students who are excited to learn programming! We'll provide mentors and a fun environment; you just come with a desire to learn. More advanced? Don't worry, CHE Hacks has got you covered too."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "CHEHacks II"

		[params.navigation.links]
			about     = "About"
			services  = "FAQ"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		# slogan     = "CHEHacks II"
		image = "true" # paths set in css file, this just needs to exist
		subtitle   = "May 13-14"
		subtitle2  = "Open the Door to Programming"
		buttonText = "Sign up"

		# About section
		[params.about]
			headline    = "Come Learn to Code"
			description = "CHE Hacks is a high school hackathon for students who are excited to learn programming!  We'll provide mentors and a fun environment; you just come with a desire to learn.  More advanced? Don't worry, CHE Hacks has got you covered too."
			buttonText  = "Get started!"


		# Service section
		[params.services]
			headline = "Frequently Asked Questions"

	    	[[params.services.list]]
	        title = "What is a hackathon?"
	        description = "A hackathon is a timed event during which students who share an enthusiasm for technology build cool things, called software or hardware \"hacks\". Although hackathons are competitions, they're fantastic learning experiences. Click [here](https://medium.com/hackathons-anonymous/what-is-a-hackathon-3d5413601c05#.10t1rwkj2) for more info."

					title2 = "What if I don't know how to code?"
					description2 = "Perfect! CHE Hacks is *the hackathon* for learning how to code, so even if you've never programmed before, don't worry! We'll have plenty of workshops to get you started and mentors to help you out."

	        title3 = "What if I'm *not* a beginner?"
	        description3 = "Great! CHE Hacks is just as open to advanced developers as it is to beginners. Looking to pursue more advanced hacks? Our mentors can help you with that too."

	        title4 = "What should I build?"
	        description4 = "Many people build games, apps, or websites. However, if you have an idea for something else, you can certainly try making it. If you don't have an idea, that's totally fine too! Either way, our mentors at the workshops can help you with your hack."

			[[params.services.list]]
					title = "How do I make a team?"
					description = "First, you can try asking other people from your school. Introduce your friends to hackathons if they haven't heard of them already! If that doesn't work, don't worry, we'll give you a chance to talk to other participants before and during CHE Hacks. If you want to, you can also work individually, but we encourage you to try to work with others for the best learning experience."

					title2 = "What should I bring?"
					description2 = "Just bring your laptop and charger! Some people choose to work for the full 24 hours, but if you plan on sleeping, you can also bring a sleeping bag and pillow."

					title3 = "What if I want to sleep?"
					description3 = "We will provide a designated sleeping area (away from noise and light) – perhaps even with air mattresses."

					title4 = "What will I eat?"
					description4 = "We’ll provide food for all meals from Saturday’s dinner to Sunday’s lunch, with plenty of snacks in between. If you have dietary restrictions, we’ll try our best to accommodate them."

			[[params.services.list]]
					title = "How do I get there?"
					description = "CHE Hacks will take place at the [Cherry Hill Public Library](https://www.google.com/maps/place/Cherry+Hill+Public+Library/@39.9205103,-75.004413,17z/data=!3m1!4b1!4m2!3m1!1s0x89c6cb0da7993605:0x6b92d74781954744). The public library is easily accessible off of I-295. Doors open at 12 PM on Saturday, and the event wraps up at 2 PM on Sunday."

					title2 = ""
					description2 = ""

					title3 = ""
					description3 = ""

					title4 = ""
					description4 = ""

	  # Portfolio modals
		[params.portfolio.modal]
	  	client = "Client"
	    date = "Date"
	    category = "Category"
	   	buttonText = "Close"

		# Contact section
		[params.contact]
			headline = "Follow Us"
			facebook = "https://www.facebook.com/CHEHacks"
			twitter = "https://twitter.com/che_hacks"
			instagram = "https://www.instagram.com/che_hacks/"

    # Google Maps section
    [params.location]
    	latitude  = "39.92046"
    	longitude = "-75.0066967"
    	maps_api_key = "AIzaSyC3kZ6gNI42yNUQQXYfxEn3ULdUb6RY0WE"
